# Generated by Django 3.1.3 on 2020-11-26 06:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scheduler', '0002_course_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now_add=True)),
                ('like_count', models.IntegerField(default=0)),
                ('star_count', models.IntegerField(default=0)),
                ('dislike_count', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('tags', models.JSONField()),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='crn',
            field=models.CharField(default=99999, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.CharField(default='default department', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='professor',
            field=models.CharField(default='john doe', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='school',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.CharField(default='9999', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='tags',
            field=models.JSONField(default='empty tag'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='time',
            field=models.JSONField(default=['0']),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='year',
            field=models.DecimalField(decimal_places=0, default=2020, max_digits=4),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.CharField(default='empty course description', max_length=2048),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now_add=True)),
                ('is_star', models.BooleanField(default=False)),
                ('year', models.DecimalField(decimal_places=0, default=2020, max_digits=4)),
                ('semester', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('note', models.TextField()),
                ('tags', models.JSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_answered', models.DateTimeField(auto_now_add=True)),
                ('like_count', models.IntegerField(default=0)),
                ('star_count', models.IntegerField(default=0)),
                ('dislike_count', models.IntegerField(default=0)),
                ('is_pin', models.BooleanField(default=False)),
                ('pin_order', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=200)),
                ('tags', models.JSONField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scheduler.course')),
            ],
        ),
        migrations.CreateModel(
            name='PostAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now_add=True)),
                ('like_count', models.IntegerField(default=0)),
                ('star_count', models.IntegerField(default=0)),
                ('dislike_count', models.IntegerField(default=0)),
                ('content', models.TextField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.post')),
                ('postee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scheduler.course'),
        ),
        migrations.AddField(
            model_name='post',
            name='poster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now_add=True)),
                ('like_count', models.IntegerField(default=0)),
                ('star_count', models.IntegerField(default=0)),
                ('dislike_count', models.IntegerField(default=0)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('tags', models.JSONField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scheduler.course')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.question')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='schedule',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='scheduler.schedule'),
            preserve_default=False,
        ),
    ]
