# Generated by Django 3.1.3 on 2020-11-26 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_auto_20201126_0550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='schedule',
        ),
        migrations.AddField(
            model_name='schedule',
            name='coursesid',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='tags',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='tags',
            field=models.JSONField(default=list),
        ),
    ]
