# Generated by Django 3.1.3 on 2020-12-22 17:24

from django.db import migrations, models
import django.db.models.deletion

#
class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0005_course_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('major', models.CharField(default='', max_length=100, null=True)),
                ('college', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(default='', max_length=300)),
                ('name', models.CharField(default='', max_length=300)),
                ('credit_hours', models.IntegerField(default=0)),
                ('school', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, default='empty course description', max_length=2048, null=True)),
                ('tags', models.JSONField(blank=True, default=list, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='course',
        ),
        migrations.RemoveField(
            model_name='course',
            name='department',
        ),
        migrations.RemoveField(
            model_name='course',
            name='description',
        ),
        migrations.RemoveField(
            model_name='course',
            name='major',
        ),
        migrations.RemoveField(
            model_name='course',
            name='name',
        ),
        migrations.RemoveField(
            model_name='course',
            name='school',
        ),
        migrations.RemoveField(
            model_name='course',
            name='tags',
        ),
        migrations.AddField(
            model_name='course',
            name='capacity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='type',
            field=models.CharField(default='lecture', max_length=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='crn',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='professor',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='time',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='question',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='course',
            name='course_meta',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='scheduler.coursemeta'),
        ),
    ]
