# Generated by Django 3.1.3 on 2020-12-23 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0006_auto_20201222_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='course',
        ),
        migrations.AddField(
            model_name='question',
            name='course_meta',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.PROTECT, to='scheduler.coursemeta'),
        ),
    ]
