# Generated by Django 3.1.3 on 2020-11-28 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0007_auto_20201128_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='crn',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.CharField(blank=True, default='empty course description', max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='major',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='tags',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
