# Generated by Django 3.1.3 on 2020-11-28 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0009_auto_20201128_0228'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('major', models.CharField(default='', max_length=100, null=True)),
                ('college', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(default='', max_length=300)),
                ('name', models.CharField(default='', max_length=300)),
                ('credit_hours', models.IntegerField(default=0)),
                ('school', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, default='empty course description', max_length=2048, null=True)),
                ('tags', models.JSONField(blank=True, default=list, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='college',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course',
        ),
        migrations.RemoveField(
            model_name='course',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='course',
            name='credit_hours',
        ),
        migrations.RemoveField(
            model_name='course',
            name='description',
        ),
        migrations.RemoveField(
            model_name='course',
            name='major',
        ),
        migrations.RemoveField(
            model_name='course',
            name='name',
        ),
        migrations.RemoveField(
            model_name='course',
            name='school',
        ),
        migrations.RemoveField(
            model_name='course',
            name='tags',
        ),
        migrations.AddField(
            model_name='course',
            name='course_meta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='scheduler.coursemeta'),
            preserve_default=False,
        ),
    ]
