# Generated by Django 3.1.3 on 2020-11-28 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0009_auto_20201128_0228'),
        ('scheduler', '0006_auto_20201128_0022'),
    ]

    operations = [
    ]
