# Generated by Django 3.1.3 on 2021-02-07 00:32

from django.db import migrations, models
import django.db.models.deletion
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0005_student_is_verified'),
        ('scheduler', '0030_auto_20210124_1952'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseChatMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('message', models.JSONField(default=dict)),
                ('course_meta', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='scheduler.coursemeta')),
                ('user', models.ForeignKey(on_delete=models.SET(user.models.Student.get_sentinel_user), to='user.student')),
            ],
        ),
    ]
