export const GET_LEADS = "GET_LEADS"
export const GET_COURSE = "GET_COURSE"
export const SET_COURSE = "SET_COURSE"
export const GET_QUE = "GET_QUE"
export const GET_NOTES = "GET_NOTES"
export const ADD_COURSE = "ADD_COURSE"
export const REMOVE_COURSE = "REMOVE_COURSE"
