# Generated by Django 3.1.3 on 2021-01-07 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201225_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='type',
            field=models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate'), ('UK', 'Unknown')], max_length=2, null=True),
        ),
    ]
