# Generated by Django 3.1.3 on 2021-01-13 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20210111_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
