# Generated by Django 3.1.3 on 2020-12-24 03:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_auto_20201224_0248'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='last_edited',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
