# Generated by Django 3.1.3 on 2020-12-26 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0006_auto_20201225_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='registered',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='course',
            name='capacity',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
    ]
