# Generated by Django 3.1.3 on 2020-12-31 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0007_auto_20201226_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='tags',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='question',
            name='tags',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='tags',
            field=models.JSONField(default=list),
        ),
    ]
