# Generated by Django 3.1.3 on 2021-01-01 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0008_auto_20201231_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='openseat',
            field=models.IntegerField(default=-1),
        ),
    ]
