# Generated by Django 3.1.3 on 2021-01-02 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0009_course_openseat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemeta',
            name='credit_hours',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
