# Generated by Django 3.1.3 on 2021-01-03 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0010_auto_20210102_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='openseat',
            field=models.IntegerField(default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='registered',
            field=models.IntegerField(default=-1, null=True),
        ),
    ]
