# Generated by Django 3.1.3 on 2021-01-03 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0011_auto_20210103_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='type',
            field=models.CharField(default='lecture', max_length=10, null=True),
        ),
    ]
