# Generated by Django 3.1.3 on 2021-01-05 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0012_auto_20210103_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='professor',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
