# Generated by Django 3.1.3 on 2021-01-10 22:18

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210107_1731'),
        ('scheduler', '0014_auto_20210105_0439'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['course_meta__title']},
        ),
        migrations.AlterModelOptions(
            name='coursemeta',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['-last_edited']},
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='coursesid',
        ),
        migrations.AddField(
            model_name='schedule',
            name='coursesid',
            field=models.ManyToManyField(to='scheduler.Course'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('coursesid', models.ManyToManyField(to='scheduler.Course')),
                ('user', models.OneToOneField(on_delete=models.SET(user.models.Student.get_sentinel_user), to='user.student')),
            ],
        ),
    ]
