# Generated by Django 3.1.3 on 2021-01-10 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0015_auto_20210110_2218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='coursesid',
            new_name='courses',
        ),
        migrations.RenameField(
            model_name='wishlist',
            old_name='coursesid',
            new_name='courses',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='semester',
            field=models.CharField(choices=[('fall', 'fall'), ('spring', 'spring'), ('summer', 'summer'), ('winter', 'winter')], max_length=8),
        ),
    ]
