# Generated by Django 3.1.3 on 2021-01-10 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0016_auto_20210110_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='tags',
            field=models.JSONField(default=list, null=True),
        ),
    ]
