# Generated by Django 3.1.3 on 2021-01-11 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0017_auto_20210110_2316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='user',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='wishlist',
            old_name='user',
            new_name='student',
        ),
    ]
