# Generated by Django 3.1.3 on 2021-01-11 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0018_auto_20210111_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='is_private',
            field=models.BooleanField(default=True),
        ),
    ]
