# Generated by Django 3.1.3 on 2021-01-11 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210107_1731'),
        ('scheduler', '0019_schedule_is_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.student', unique=True),
        ),
    ]
