# Generated by Django 3.1.3 on 2021-01-11 01:38

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210107_1731'),
        ('scheduler', '0020_auto_20210111_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='courses',
            field=models.ManyToManyField(blank=True, to='scheduler.Course'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='student',
            field=models.OneToOneField(on_delete=models.SET(user.models.Student.get_sentinel_user), to='user.student'),
        ),
    ]
