# Generated by Django 3.1.3 on 2021-01-12 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0022_auto_20210111_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='events',
            field=models.JSONField(default=list, null=True),
        ),
    ]
