# Generated by Django 3.1.3 on 2021-01-14 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0025_auto_20210113_0230'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='custom',
            field=models.JSONField(default=list, null=True),
        ),
    ]
