# Generated by Django 3.1.3 on 2021-01-14 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0026_wishlist_custom'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='custom',
            field=models.JSONField(default=list, null=True),
        ),
    ]
