# Generated by Django 3.1.3 on 2021-01-14 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0027_schedule_custom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='name',
            field=models.CharField(blank=True, default='Default schedule', max_length=200),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='note',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='semester',
            field=models.CharField(choices=[('fall', 'fall'), ('spring', 'spring'), ('summer', 'summer'), ('winter', 'winter')], default='fall', max_length=8),
        ),
    ]
