# Generated by Django 3.1.3 on 2021-01-24 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0028_auto_20210114_0424'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='coursemeta',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
