# Generated by Django 3.1.3 on 2021-01-24 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0029_auto_20210124_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='openseat',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='registered',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
    ]
