# Generated by Django 3.1.3 on 2021-02-23 04:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0031_auto_20210223_0336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='course',
        ),
        migrations.AddField(
            model_name='tag',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='count',
            field=models.PositiveIntegerField(default=0, verbose_name='tag count'),
        ),
    ]
