# Generated by Django 3.1.3 on 2021-02-24 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0033_auto_20210223_0415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='last_edited',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='postanswer',
            name='last_edited',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
