# Generated by Django 3.1.3 on 2021-03-01 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20210301_0351'),
        ('scheduler', '0035_auto_20210224_0259'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='dislike',
            field=models.ManyToManyField(blank=True, related_name='post_dislike', to='user.Student'),
        ),
        migrations.AddField(
            model_name='post',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='post_like', to='user.Student'),
        ),
        migrations.AddField(
            model_name='post',
            name='star',
            field=models.ManyToManyField(blank=True, related_name='post_star', to='user.Student'),
        ),
        migrations.AddField(
            model_name='postanswer',
            name='dislike',
            field=models.ManyToManyField(blank=True, related_name='postanswer_dislike', to='user.Student'),
        ),
        migrations.AddField(
            model_name='postanswer',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='postanswer_like', to='user.Student'),
        ),
        migrations.AddField(
            model_name='postanswer',
            name='star',
            field=models.ManyToManyField(blank=True, related_name='postanswer_star', to='user.Student'),
        ),
    ]
